version: "3.9"
services:
  gmtasker_db:
    build:
      context: ./Db
      dockerfile: Dockerfile
    environment:
      - MYSQL_ROOT_PASSWORD=123123
    ports:
      - "3307:3306"
  gmtasker_api:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - gmtasker_db
    ports:
      - "80:80"